### ISSUE TITLE
How to filter Tags using InstancesClient.list()?

### ISSUE THREAD

**Issue by smoolya17** [googleapis/python-compute#115]
I am trying to fetch billing inventory reports for which i need to only filter compute instances with ccp_managed tag. Any google cloud python expert could you please recommend the appropriate way to extract it?

**Comment by busunkim96** [comment]
Hi @smoolya17,

It does not look like it is possible to create [filter expressions](https://cloud.google.com/compute/docs/reference/rest/v1/instances/list) based on tags through the REST API (which this library wraps).

The gcloud command [`gcloud compute instances list`](https://cloud.google.com/sdk/gcloud/reference/compute/instances/list) appears to provide support for [filtering items in lists](https://cloud.google.com/sdk/gcloud/reference/topic/filters) so you could try that as a workaround.

@rsamborski @FrodoTheTrue Is there a good way to do this that you know of? Are there plans to support more complex filter expressions in the Compute API?

**Comment by m-strzelczyk** [comment]
First of all let's clarify. @smoolya17 do you really mean tags, as in [this document](https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing) ("A tag is a key-value pair that can be attached to an organization, folder, or project.")? Or perhaps what you have in mind is [labels](https://cloud.google.com/compute/docs/labeling-resources) which are attached to GCE instances?

For tags - there is nothing I can do, they don't really work on this level.

For labels:
Labels are a <key, value> pairs, you mention only `ccp_managed`, I'm assuming that's a key with no value.

You can filter your instances like this:

```python
import google.cloud.compute_v1 as compute_v1

ir = compute_v1.ListInstancesRequest()
ir.project = 'your-project-name'
ir.zone = 'your-zone'
ir.filter = 'labels.gcc_managed:*'

instances_client = compute_v1.InstancesClient()
instances = instances_client.list(ir)
```

WARNING!!! This will give you all instances with the `gcc_managed` label, no matter the value, so `gcc_managed: true` as well as `gcc_managed: false`. If you want to filter for specific key-value pair, just do `labels.gcc_managed=true` for example.

I guess we should provide those examples in a more accessible way... It took me far too long to figure out how to filter for labels without specifying concrete value.

**Comment by smoolya17** [comment]
@m-strzelczyk what I was referring to was labels and not tags. This code snippet which you used to explained reduces my code complexity wherein I don't need to iterate through the labels.

Any tests or documentation towards using the compute engine library in the above manner is not mentioned anywhere, so could you kindly reference a documentation page on using the compute_v1 library?

Thanks

**Comment by smoolya17** [comment]
The above snippet should solve my issue

**Comment by m-strzelczyk** [comment]
Yes, we will be updating the code samples and documentation pages to include this information. Currently it's not mentioned anywhere explicitly, I had to do some trial and error testing to figure this out, based on documents not really related the API.

**Comment by smoolya17** [comment]
Since the above code snippet sobbed my issue I am closing the ticket
