### ISSUE TITLE
Cannot resize to 0 instances

### ISSUE THREAD

**Issue by igor-solomatov** [googleapis/python-compute#12]
Hi All,

If target size of the region instance group is 0, resize fails with bad request, since `?size=0` parameter is removed

The following check should be `if v is not None` currently it is `if v` and 0 equals to False in Python.

https://github.com/googleapis/python-compute/blob/16e7294cd536af9a8bf8e4e99219a883339aa955/google/cloud/compute_v1/services/region_instance_group_managers/transports/rest.py#L1339

**Comment by parthea** [comment]
@yon-mg PTAL

**Comment by vchudnov-g** [comment]
A fix for this is forthcoming

**Comment by busunkim96** [comment]
@vchudnov-g Has this been addressed? (Just checking as the issue is now OOSLO)

**Comment by busunkim96** [comment]
Update: @vam-google confirmed a fix has landed in the generator. I am working on re-generating the library right now.

**Comment by busunkim96** [comment]
This should be fixed in the latest release `google-cloud-compute==0.5.0`.
