### ISSUE TITLE
Missing `priority` parameters in security_policies client

### ISSUE THREAD

**Issue by TheJokersThief** [googleapis/python-compute#173]
#### Steps to reproduce

  1. Try to use `patch_rule_unary`
  2. Receive error because a priority wasn't specified

#### Code example

```python
from google.cloud.compute_v1.services.security_policies.client import SecurityPoliciesClient
from google.cloud.compute_v1.types import compute

client = SecurityPoliciesClient()

rule = compute.SecurityPolicyRule(
            action="allow", 
            preview=True, 
            description="Allow traffic",
            match=compute.SecurityPolicyRuleMatcher(expr=compute.Expr(expression="request.path.matches('/api/')")),
            priority=1
            )

client.patch_rule_unary(project="<redacted>", security_policy="<redacted>", security_policy_rule_resource=rule)
```

#### Stack trace
```
google.api_core.exceptions.BadRequest: 400 POST https://compute.googleapis.com:443/compute/v1/projects/<redacted>/global/securityPolicies/<redacted>/patchRule: Invalid value for field 'priority': '0'. <redacted> does not contain a rule at priority 0.
```

I'm just following the recommended steps, but I think this issue is straightforward :)

**Comment by parthea** [comment]
Hi @TheJokersThief,

Thanks for reporting this issue and providing a code snippet. I was able to reproduce the issue locally. The code is generated automatically using [gapic-generator-python](https://github.com/googleapis/gapic-generator-python) so I need to confirm if this is an issue with the code generator. In the meantime, I was able to get `patch_rule_unary` to work using the following code: 

```
from google.cloud.compute_v1.services.security_policies.client import SecurityPoliciesClient
from google.cloud.compute_v1.types import compute, SecurityPolicyRuleMatcherConfig, SecurityPolicyRuleMatcher

client = SecurityPoliciesClient()

rule = compute.SecurityPolicyRule()
rule.action = "allow"
rule.preview = True
rule.description= "Allow traffic"
rule.match=compute.SecurityPolicyRuleMatcher(expr=compute.Expr(expression="request.path.matches('/api/')"))
rule.priority=1

request = compute.PatchRuleSecurityPolicyRequest()
request.project = <redacted>
request.security_policy=<redacted>
request.security_policy_rule_resource = rule
request.priority=1

client.patch_rule_unary(request=request)
```

Please let me know if you still receive an error using the above code snippet.

**Comment by TheJokersThief** [comment]
Yep, that's how I'd already worked around it - I just wanted to fix the flat arguments so there wasn't any confusion in future for anyone else

**Comment by parthea** [comment]
Googlers see internal issue b/211453570

**Comment by parthea** [comment]
b/211453570 was closed as fixing this bug would be a breaking change to the apiary client, which is already stable. I'll keep this bug open for visibility. I'm also going to bump this to P2 as there is a workaround.

**Comment by parthea** [comment]
I'm going to close this as the fix would require a breaking change as per b/211453570.
