### ISSUE TITLE
Please fix this typo

### ISSUE THREAD

**Issue by savijatv** [googleapis/python-compute#194]
https://github.com/googleapis/python-compute/blob/a93807a5c9680af775da0b3859485acd3e123f3a/samples/snippets/sample_start_stop.py#L106

Stops a stopped Google Compute Engine instance. >> Shouldn't this read 'Stops a started Google Compute Engine instance.'?

**Comment by busunkim96** [comment]
@m-strzelczyk Please take a look and edit the docstring as necessary. Thank you!
