### ISSUE TITLE
Problem with Compute > Subnetworks module 

### ISSUE THREAD

**Issue by vdmaxi4** [googleapis/python-compute#207]
#### Environment details

  - OS type and version: CentOS Linux 8
  - Python version: Python 3.6.8
  - pip version: pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
  - `google-cloud-compute` version: 
                        Name: google-cloud-compute
                        Version: 1.0.0
                        Summary: UNKNOWN
                        Home-page: https://github.com/googleapis/python-compute
                        Author: Google LLC
                        Author-email: googleapis-packages@google.com
                        License: Apache 2.0
                        Location: /usr/local/lib/python3.6/site-packages
                        Requires: google-api-core, proto-plus
                        Required-by:

#### Steps to reproduce

  1. Create VPC network with subnetwork and "Flow logs = Off" from Google Web Console
  2. Patch subnetwork with "enable_flow_logs = True" from python script

#### Code example

```python
from google.cloud import compute_v1
client = compute_v1.SubnetworksClient()

subnetworks = subnetwork_client.list_usable(project=project_id)
for subnetwork in subnetworks:
    region = str(subnetwork.subnetwork).split('/')[8]
    subnetwork_name = str(subnetwork.subnetwork).split('/')[10]
    subnetwork_resource = subnetwork_client.get(project=project_id, region=region, subnetwork=subnetwork_name)
    subnetwork_resource.enable_flow_logs = True
    subnetwork_client.patch_unary(project=project_id, region=region, subnetwork=subnetwork_name, subnetwork_resource=subnetwork_resource)
```

If you exec this python code you will get error :
google.api_core.exceptions.BadRequest: 400 PATCH https://compute.googleapis.com:443/compute/v1/projects/project_id/regions/us-west1/subnetworks/test2:.
Invalid value for field 'resource.enableFlowLogs': 'false'. If enable flow logging and enable in LogConfig are both set, they must also match.
'

If you try to patch with log_config option like:
```
from google.cloud import compute_v1
client = compute_v1.SubnetworksClient()

subnetworks = subnetwork_client.list_usable(project=project_id)
for subnetwork in subnetworks:
    region = str(subnetwork.subnetwork).split('/')[8]
    subnetwork_name = str(subnetwork.subnetwork).split('/')[10]
    subnetwork_resource = subnetwork_client.get(project=project_id, region=region, subnetwork=subnetwork_name)
    subnetwork_resource.enable_flow_logs = True
    subnetwork_resource.log_config = {'enable': True, 'metadata': "INCLUDE_ALL_METADATA", 'aggregation_interval': "INTERVAL_15_MIN", 'flow_sampling': 0.5}
    subnetwork_client.patch_unary(project=project_id, region=region, subnetwork=subnetwork_name, subnetwork_resource=subnetwork_resource)
```
you will get error:
google.api_core.exceptions.BadRequest: 400 PATCH https://compute.googleapis.com:443/compute/v1/projects/project_id/regions/us-west1/subnetworks/test2:.
Invalid value for field 'resource': '{  "name": "test2",  "description": "",  "network": "https://www.googleapis.com/compute/v1/projects/...'..
Only one field at a time can be modified in the request. The modified fields were: [enableFlowLogs, logConfig].

There is no methods like update, only patch_unary. So how can I enable flow logs with python library???
Thanks!

**Comment by busunkim96** [comment]
Hi @vdmaxi4,

Thank you for the report!

I looked into this internally and found someone reporting the same issue (Googlers see 148202237). The Compute API engineer stating that `enableFlowLogs` is deprecated and that you should just use the `enable` field inside `logConfig`.

Could you try this?

```py
from google.cloud import compute_v1
client = compute_v1.SubnetworksClient()

subnetworks = subnetwork_client.list_usable(project=project_id)
for subnetwork in subnetworks:
    region = str(subnetwork.subnetwork).split('/')[8]
    subnetwork_name = str(subnetwork.subnetwork).split('/')[10]
    subnetwork_resource = subnetwork_client.get(project=project_id, region=region, subnetwork=subnetwork_name)
    subnetwork_resource.log_config = {'enable': True, 'metadata': "INCLUDE_ALL_METADATA", 'aggregation_interval': "INTERVAL_15_MIN", 'flow_sampling': 0.5}
    subnetwork_client.patch_unary(project=project_id, region=region, subnetwork=subnetwork_name, subnetwork_resource=subnetwork_resource)
```

That said, I recognize the error messages are a bit cryptic, it's unclear to me why you get the first error (maybe `logConfig.enable` is defaulting to `True`?) and there is no mention of `enableFlowLogs` being deprecated in https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks/patch. I'll follow up with the Compute API folks to see if the documentation can be updated.

**Comment by busunkim96** [comment]
Please disregard my last comment.

It looks like the API expects the `patch` call to only set fields that are changed. This is a reasonable assumption for those making REST requests directly. However, folks calling this method through any library are most likely going to retrieve the subnetwork resource through a `get`, modify some fields, and then pass it to `patch`. (Especially given that `fingerprint` is a required parameter and can only be obtained through `get`). 

In addition, I'm not sure the library can distinguish between unset fields that default to `False` and those that have explicitly been set to `False`.

I'll investigate a bit more and update in a bit.

**Comment by busunkim96** [comment]
It looks like the library _does_ distinguish unset fields. 

The code snippet below creates a new `Subnetwork` object, copies over the `fingerprint` (required for patch calls), and sets `log_config.enable=True`. This way you can avoid having both `log_config.enable` and `enableFlowLogs` present on the HTTP request.

```py
from google.cloud import compute_v1

subnetwork_client = compute_v1.SubnetworksClient()
project_id = "my-project-id"

subnetworks = subnetwork_client.list_usable(project=project_id)
for subnetwork in subnetworks:
    region = str(subnetwork.subnetwork).split('/')[8]
    subnetwork_name = str(subnetwork.subnetwork).split('/')[10]
    subnetwork_resource = subnetwork_client.get(project=project_id, region=region, subnetwork=subnetwork_name)
    
    # Create a new subnetwork and only set the fields we want to change
    patch_subnetwork = compute_v1.Subnetwork()
    patch_subnetwork.log_config.enable = True
    # fingerprint is required for 'patch' request
    patch_subnetwork.fingerprint = subnetwork_resource.fingerprint
    subnetwork_client.patch_unary(project=project_id, region=region, subnetwork=subnetwork_name, subnetwork_resource=patch_subnetwork)
```

**Comment by vdmaxi4** [comment]
Hello! Seems it works fine! Thanks a lot )
And it works with the request field

request = types.PatchSubnetworkRequest(project=project_id, region=region, subnetwork=subnetwork_name, subnetwork_resource=values_subnetwork_enable_flow_logs)

subnetwork_client.patch_unary(request=request)

**Comment by busunkim96** [comment]
@vdmaxi4 Glad to hear that worked for you! 

I've also contacted the Compute API to ask if the behavior can be changed on their end - the snippet you shared seems like a normal way to call `patch_unary`. (Googlers see issue 217972397.)

Thanks again for the detailed original report, it was super helpful for tracking down what was happening. :)
