### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by savijatv** [googleapis/python-compute#223]
https://github.com/googleapis/python-compute/blob/65a1149437416aa73d52225aa492449c72ea5eb6/samples/snippets/sample_start_stop.py#L41

name of the instance your want to reset >> name of the instance you want to reset

**Comment by busunkim96** [comment]
@savijatv Thanks for filing an issue! For small typos, feel free to go straight to opening a PR and we will be happy to review. :)
