### ISSUE TITLE
Regional instance bulk create API doesn't work

### ISSUE THREAD

**Issue by ntabris** [googleapis/python-compute#224]
#### Environment details

  - OS type and version: MacOS 12.0.1
  - Python version: **3.8.12**
  - pip version: **22.0.3**
  - `google-cloud-compute` version: **1.0.0**

#### Steps to reproduce

In at least some circumstances, the `bulk_insert_unary` method on `compute_v1.RegionInstancesClient` doesn't create a request body with the data the API expects.

In particular, I'm trying bulk create instances from an instance template and I get back a `400` response with the message `Invalid value for field 'region': 'us-east1'. Unknown region.`.

After much debugging, I compared the `http-log` from the `gloud` cli performing the same action, and the request body is different than what the Python client is sending.

The request body from `gcloud` that works looks like this:

```
{"count": "2", "instanceProperties": {}, "minCount": "2", "namePattern": "foo-#", "perInstanceProperties": {}, "sourceInstanceTemplate": "https://compute.googleapis.com/compute/v1/projects/gcp-ch-01/global/instanceTemplates/foobar0-scheduler"}
```

while the request body from `bulk_insert_unary` that doesn't work is missing `"instanceProperties": {}` and `"perInstanceProperties": {}`. I spent some time hacking the Python client and found that if I forced it to add `"instanceProperties":{}` to the request body, the call worked (got back a `200` and created the instances).

Note that changing `False` to `True` in this line doesn't fix the problem:

https://github.com/googleapis/python-compute/blob/main/google/cloud/compute_v1/services/region_instances/transports/rest.py#L205

Setting `including_default_value_fields` to `True` makes it include `"perInstanceProperties": {}` (which doesn't matter) but still not include `"instanceProperties":{}` (which is what is needed).

In case it matters, I really do want the regional endpoint because I want it to choose the best zone for me (and I also want all the instances in the same zone, so a Managed Instance Group is not what I want).

#### Code example

Here's a snippet, obviously you'll need to use your own creds and instance template.

```python
instance_client = compute_v1.RegionInstancesClient(credentials=credentials)

bulk_resource = compute_v1.BulkInsertInstanceResource()
bulk_resource.count = 2
bulk_resource.min_count = 1
bulk_resource.name_pattern = f"foo-#"
bulk_resource.source_instance_template = "https://compute.googleapis.com/compute/v1/projects/foobar-project/global/instanceTemplates/foobar0-scheduler"

op = instance_client.bulk_insert_unary(
    project=project_name,
    region=region,
    bulk_insert_instance_resource_resource=bulk_resource
)
```

**Comment by ntabris** [comment]
In the meantime, adding this is a work-around:

```python
bulk_resource.instance_properties = compute_v1.InstanceProperties()
bulk_resource.instance_properties.description = ""
```

**Comment by busunkim96** [comment]
Thanks for the detailed bug report @ntabris.

I don't see anything in the API documentation saying `instanceProperties` is required, the [docs](https://cloud.google.com/compute/docs/reference/rest/v1/regionInstances/bulkInsert
) only say:

> The instance properties defining the VM instances to be created. Required if `sourceInstanceTemplate` is not provided.


In this case a `sourceInstanceTemplate` _is_ provided, so it seems like `instanceProperties` should be completely optional. I can also reproduce the error using the "Try this method" interface on https://cloud.google.com/compute/docs/reference/rest/v1/regionInstances/bulkInsert. 

I'm going to reach out to some Compute API folks to see what's happening here.

**Comment by ntabris** [comment]
Thanks! On reflection this seems like more of a bug with the endpoint (especially since the error message it returns is just wrong), so if you can get the API folks to fix it that would be great, but at any rate it would be nice if client and API agreed :-)

**Comment by busunkim96** [comment]
Quick followup, the Compute API Engineer has confirmed this is a bug is now working on fixing it. Please continue using the workaround shared in https://github.com/googleapis/python-compute/issues/224#issuecomment-1046148639.

**Comment by busunkim96** [comment]
The fix has been released to production.
