### ISSUE TITLE
Set delete protection default to true

### ISSUE THREAD

**Issue by rsamborski** [googleapis/python-compute#272]
The sample shows how to use delete protection, but by default the [flag is set to false](https://github.com/googleapis/python-compute/blob/4da8b52b257403f50766625eaecf9173f9940828/samples/snippets/instances/delete_protection/create.py#L146). In NodeJS and Java we set this flag to true, so I suggest to the same in this case.

**Comment by m-strzelczyk** [comment]
The way Python samples are build, changing the default value in the line you pointed to would result in changing it in almost every sample that creates a VM. The `create_instance` is an ["ingredient"](https://github.com/googleapis/python-compute/blob/4da8b52b257403f50766625eaecf9173f9940828/samples/ingredients/instances/create_instance.py) function and is used in multiple other samples in which the default setting of `delete_protection` being `False` makes more sense.

The function is properly called in [`create_protected_instance`](https://github.com/googleapis/python-compute/blob/4da8b52b257403f50766625eaecf9173f9940828/samples/snippets/instances/delete_protection/create.py#L249) function that sets the protection flag to `True`.

If the sample wasn't built from shared pieces, then I'd agree that we should change the default value.
