### ISSUE TITLE
Add sample for BulkInsertInstanceResource.per_instance_properties

### ISSUE THREAD

**Issue by ntabris** [googleapis/python-compute#278]
It's not remotely obvious how to use `BulkInsertInstanceResource.per_instance_properties`.

Here are the somewhat unhelpful docs:

https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.types.BulkInsertInstanceResource

Eventually I figured out that I needed to do something like this:

```python
    bulk_resource.per_instance_properties = {
        f"foo-{i}":
            compute_v1.BulkInsertInstanceResourcePerInstanceProperties(name=f"foo-{i}")
        for i in range(10)
    }
```

It's especially non-obvious since the docs on `BulkInsertInstanceResourcePerInstanceProperties` (https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.types.BulkInsertInstanceResourcePerInstanceProperties) explicitly say "Do not use" for `name`. But without this, I keep getting errors related to building the `BulkInsertInstanceResource` protobuf.

Maybe it would be helpful to other people to have a sample. Making the docs better would also be nice.

**Comment by m-strzelczyk** [comment]
Yes, we accept PRs from outside Google :) At least for the samples part of repository, as the code part is actually auto-generated, so it wouldn't make much sense.

**Comment by ntabris** [comment]
> It's generally advised to use the `name_pattern` field for the `BulkInsertInstanceResource` and just leave the `per_instance_properties` empty

While that might generally be a good idea, the problem here is that there appears to be a race condition in how the names are generated server side, such that if I have multiple bulkInsert operations in flight at the same time, *some* of the instances fail saying they already exist and I don't end up with the desired total number of instances (in particular, some of the individual instance operations get `RESOURCE_ALREADY_EXISTS` errors).

I opened an internal support ticket about this and was told

> From my understanding as per the documentation [1],  when using name_pattern GCE is generating the names and it is trying to avoid name conflicts by only checking up front. As provided in the example, if there exists an instance with name inst-0050, then instance names generated using the pattern inst-#### begin with inst-0051. So, there is a possibility that race conditions could occur when multiple API calls are generated around the same time.

After that response the support ticket was closed, so as far as I know there's still a race condition.

When I switched from using `name_pattern` to explicitly specifying a name for each instance in the bulk request, I stopped getting `RESOURCE_ALREADY_EXISTS` errors when I had multiple in-flight bulk operations.

**Comment by ntabris** [comment]
Also, looking at the API (rather than client) docs, I see no indication that specifying per instance properties is deprecated or anything like that:

https://cloud.google.com/compute/docs/reference/rest/v1/instances/bulkInsert

Likewise, the guide about creating VMs in bulk explicitly tells you (in pseudo-code) to use per instance properties to set names:

https://cloud.google.com/compute/docs/instances/multiple/create-in-bulk#create_vms_in_bulk_and_view_their_status

So as far as I can tell this is a supported and recommended part of the API, it's just that the client library isn't doing a good job exposing this (important) part of the API.
