### ISSUE TITLE
Instance Group Python Scripts

### ISSUE THREAD

**Issue by fo250061** [googleapis/python-compute#302]
Please, i will like a python script that will do the following:
1. restart an instance group
2. replace and instance group
3. disable the health-check of instance group
4. enable health-check of instance group
5. describe an instance. 

These commands are available via gcloud as: 
1. gcloud compute instance-groups managed describe INSTANCE-GROUP --region REGION
2. gcloud compute instance-groups managed rolling-action replace INSTANCE GROUP --region REGION--max-surge NUMBER --max-unavailable NUMBER --replacement-method=RECREATE
3. gcloud compute instance-groups managed update INSTANCE-GROUP --clear-autohealing --region=REGION
4. gcloud compute instance-groups managed update INSTANCE GROUP --health-check=HEATH-CHECK-NAME --initial-delay=300 --region=REGION
5. gcloud compute instance-groups managed describe INSTANCE-GROUP --region REGION

My original intention was to run the gcloud in cloud function, but currently that is not possible. So, I will like a python script that will allow me to do the same

**Comment by parthea** [comment]
@m-strzelczyk, are you aware of any samples that cover these items?

**Comment by m-strzelczyk** [comment]
We don't have samples that would cover those things. I will try to provide a veeery basic instructions that might be enough for @fo250061 to use to write the code they want.

1. [Describing an instance](https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.services.instance_group_managers.InstanceGroupManagersClient#google_cloud_compute_v1_services_instance_group_managers_InstanceGroupManagersClient_get):
```python
client = compute_v1.InstanceGroupManagersClient()
group_info = client.get(project=PROJECT_ID, zone=ZONE, instance_group_manager=NAME_OF_THE_GROUP)
```
This will give you an object describing the managed group. There's a similar Client and `get` method for [regional groups](https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.services.region_instance_group_managers.RegionInstanceGroupManagersClient#google_cloud_compute_v1_services_region_instance_group_managers_RegionInstanceGroupManagersClient_get).

2. Replacing - this is done by calling [`patch`](https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.services.region_instance_group_managers.RegionInstanceGroupManagersClient#google_cloud_compute_v1_services_region_instance_group_managers_RegionInstanceGroupManagersClient_patch) method for the instance groups, for your example, you'll need to create a request with body similar to this:
```json
{"updatePolicy": {"maxSurge": {"fixed": 1}, "maxUnavailable": {"fixed": 1}, "minimalAction": "REPLACE", "replacementMethod": "RECREATE", "type": "PROACTIVE"}, "versions": [{"instanceTemplate": "https://www.googleapis.com/compute/v1/projects/mestiv-playground/global/instanceTemplates/mig-template", "name": "0/2022-07-21 14:09:55.895943+00:00", "targetSize": {"calculated": 1}}]}
```
This will create a new version of the group, forcing it to recreate the instances.

3. Updating - this is done by calling `patch` as well. Just set `autoHealingPolicies` to empty list.

4. Setting health check for an instance group is done by `patch` as well. 
If you have problems with figuring out the proper values for different fields etc. Try using `--log-http` flag for the `gcloud` version of what you want to do. Then you can replicate the requests with the library.


Samples for managed instance groups in general will be eventually available, but it won't be any time soon. Let me know if you have any problems with implementing what I described, I'll help if you have any problems/questions.
