### ISSUE TITLE
Use proxy with clients

### ISSUE THREAD

**Issue by zhangtai** [googleapis/python-compute#318]
I want to use proxy when querying GCP resources, because there are some restrictions of network in my working environment, I didn't find any info regarding this in the docs or codes, can you please if this feature exists or not? Will you consider to implement it if not? Thanks.

**Comment by vam-google** [comment]
To the best of my knowledge, Pytohn Google Cloud Libraries do not have special support for proxies out of the box. This is also somewhat confirmed on stackwoverflow: https://stackoverflow.com/questions/45173466/google-cloud-storage-client-library-behind-proxy-access-bucket-objects-using. I also could not find any proxy-related code in neither of these: gapic-generator, proto-plus, python-api-core libraries (which constitute a typical python client lib for google cloud).

@parthea Are you aware of any proxy support provided by gapic python libs?

Closing this issue. Feel free to reopen, if there is any new info on proxy support.
